version: '3.8'

services:
  # 主GPU工作环境
  pointcloud-style-transfer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pointcloud-style-transfer
    hostname: pc-style-server
    stdin_open: true
    tty: true
    
    # GPU配置
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    # 端口映射
    ports:
      - "8888:8888"   # Jupyter Lab
      - "6006:6006"   # TensorBoard
      - "8080:8080"   # 可视化服务
      - "5000:5000"   # Flask应用
      - "8501:8501"   # Streamlit

    # 文件系统挂载
    volumes:
      # 项目代码
      - .:/workspace
      # 数据目录
      - ./datasets:/workspace/datasets
      - ./checkpoints:/workspace/checkpoints
      - ./logs:/workspace/logs
      - ./results:/workspace/results
      # 主机home目录（可选）
      - ${HOME}:/host-home
      # X11支持（Linux GUI）
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri

    # 工作目录
    working_dir: /workspace

    # 环境变量
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
      - JUPYTER_ENABLE_LAB=yes
      - PYTHONPATH=/workspace
      - QT_X11_NO_MITSHM=1

    # 系统配置
    shm_size: 16g
    ulimits:
      memlock: -1
      stack: 67108864

    # 网络
    networks:
      - pointcloud-net

    # 启动命令
    command: /bin/bash

    # 设备访问
    devices:
      - /dev/dri:/dev/dri

    # 用户配置（与宿主机用户一致）
    user: "1000:1000"

  # Jupyter Lab服务
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pc-jupyter
    ports:
      - "8889:8888"
    volumes:
      - .:/workspace
      - ./datasets:/workspace/datasets
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PYTHONPATH=/workspace
    working_dir: /workspace
    command: >
      jupyter lab 
      --ip=0.0.0.0 
      --port=8888 
      --no-browser 
      --allow-root 
      --NotebookApp.token='' 
      --NotebookApp.password=''
      --ServerApp.allow_origin='*'
      --ServerApp.allow_remote_access=True
    networks:
      - pointcloud-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # TensorBoard服务
  tensorboard:
    image: tensorflow/tensorflow:latest-gpu
    container_name: pc-tensorboard
    ports:
      - "6007:6006"
    volumes:
      - ./logs:/logs
      - ./experiments:/experiments
    command: >
      tensorboard 
      --logdir=/logs 
      --host=0.0.0.0 
      --port=6006 
      --bind_all
      --reload_interval=30
    networks:
      - pointcloud-net

  # 开发数据库（可选 - 存储实验元数据）
  mongodb:
    image: mongo:6.0
    container_name: pc-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pointcloud123
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - pointcloud-net

networks:
  pointcloud-net:
    driver: bridge

volumes:
  mongodb_data:
    driver: local

# 预设配置模板
x-gpu-config: &gpu-config
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

x-common-volumes: &common-volumes
  - .:/workspace
  - ./datasets:/workspace/datasets
  - ./checkpoints:/workspace/checkpoints
  - ./logs:/workspace/logs

x-common-env: &common-env
  PYTHONPATH: /workspace
  NVIDIA_VISIBLE_DEVICES: all
  CUDA_VISIBLE_DEVICES: 0